server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  prefix: /jxwy    #
  # 忽略所有的微服务名称访问。比如原来可以这样访问，http://springcloud/... 现在只能http://myzuul.com/
  ignored-services: "*"
  routes:
    mydept.serviceId: springcloud-provider
    mydept.path: /mydept/**