server:
  port: 8002
#  servlet:
#    context-path: /springcloud # 请求的前缀

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddb02?characterEncoding=UTF-8&&useSSL=false&serverTimezone=UTC&&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #对外暴露的微服务名称
  application:
    name: springcloud-provider
mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml   # yaml 数组 相当于  mybatis.mapper-locations[0].classpath=...

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider8002 #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
