spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/mybatis_plus?characterEncoding=UTF-8&&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver