spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/mybatis_plus?characterEncoding=UTF-8&&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
        slave_1:
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/mybatis_plus2?characterEncoding=UTF-8&&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true


